### ISSUE TITLE
Usage With Redux

### ISSUE THREAD

**Issue by ibrahim-amer** [romaindso/react-feature-flags#1]
I want to know how this thing is connected with redux

**Comment by romaindso** [comment]
Hi,
The `<FlagsProvider>` component accept a props `value` that is an array of flags 
https://github.com/romaindso/react-feature-flags#flagsprovider

That value can comes from a Redux store by using the Redux `connect` method in the component that render the `<FlagsProvider>` component. All you need is the `mapStateToProps` method to read the array of flags from the store and inject it through that parent component.
